export { default as Hero } from './Hero-page'
export { default as Discover } from './Discover'
export { default as Description } from './Description'
export { default as Events } from './Events'
export { default as Faq } from './Faq'
export { default as Involved } from './Involved'